/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;

/**
 *
 * @author GIGABYTE
 */
public class Plot2D extends javax.swing.JPanel {

    /**
     * Creates new form Plot2D
     */
    public Plot2D() {
        initComponents();
    }
    
    public void paintComponent(Graphics g){
        Graphics2D g2d = (Graphics2D)g.create();
        super.paintComponent(g2d);
        g2d.setColor(new Color(235, 234, 235));
        Stroke stroke = new BasicStroke(1, BasicStroke.CAP_BUTT,
                BasicStroke.JOIN_BEVEL, 0, new float[]{9}, 0);
        g2d.setStroke(stroke);
        int k = 50;
        for(int i = 0; i <= this.getWidth(); i += k)
            g2d.drawLine(i, 0 , i, this.getHeight());
        for(int i = 0; i <= this.getHeight(); i += k)
            g2d.drawLine(0, i, this.getWidth(), i);
        g2d.setColor(new Color(21, 104, 237));
        g2d.drawLine(0, this.getHeight(), this.getWidth(), 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
